cicd: add healthcheck for backend gha

diff --git a/.github/workflows/deploy-backend.yml b/.github/workflows/deploy-backend.yml
--- a/.github/workflows/deploy-backend.yml
+++ b/.github/workflows/deploy-backend.yml
@@ -79,9 +79,20 @@ jobs:
         with:
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          application_name: cvai-app
-          environment_name: cvai-env
+          application_name: ${{ vars.EB_APP_NAME }}
+          environment_name: ${{ vars.EB_ENVIRONMENT_NAME }}
           region: ${{ vars.AWS_REGION }}
           version_label: "deploy-${{ github.sha }}-${{ github.run_id }}"
           deployment_package: deploy.zip
           use_existing_version_if_available: true
+
+      - name: Wait for deployment to finish
+        run: |
+          aws elasticbeanstalk wait environment-updated \
+            --environment-name ${{ vars.EB_ENVIRONMENT_NAME }} \
+            --region ${{ vars.AWS_REGION }}
+
+      - name: Health check
+        run: |
+          HEALTH_URL="http://${{ vars.EB_ENVIRONMENT_NAME }}.${{ vars.AWS_REGION }}.elasticbeanstalk.com/healthcheck"
+          curl --fail $HEALTH_URL || (echo "Deployment health check failed" && exit 1)
